name: "docs-html-mdx-transform"
description: "Transforms the output of dokkaHtml or Jazzy to mdx files"
inputs:
  src:
    description: "The path of the packages output of dokkaHTML or Jazzy, typically something like build/dokka/html"
    required: true
  modules:
    description: "The modules of the project, typically the folders in src"
    required: true
  dest:
    description: "The path where to copy the generated files"
    required: true
  folder:
    description: "Name of the folder in dest which is created to store the output"
    required: true
runs:
  using: "node16"
  main:  "index.js"